### ISSUE TITLE
not work in avs 2.6

### ISSUE THREAD

**Issue by realfinder** [Asd-g/yadifmod2#2]
hi
with yadifmod2()
I get
![image](https://user-images.githubusercontent.com/2512153/85978929-4cc8ca00-b9e8-11ea-8fef-8b6d3bf6987f.png)
in avs 2.6 and if I set the opt to 4 it work fine

**Comment by Asd-g** [comment]
Please try 0.2.6.

**Comment by realfinder** [comment]
this work now, thanks
