### ISSUE TITLE
Improved motion interpolation using RIFE

### ISSUE THREAD

**Issue by ryanfelder** [Asd-g/yadifmod2#6]
Hey there, have you ever considered using some of the newer frame interpolation ML solvers to improve on the performance of deinterlacing filters?

I've done some experiments with this on my own, 

- split a video into png frames
- split the pngs into two half height pngs, one with even lines, the other with odd lines
- interpolate each set to 2x framerate with RIFE
- scale images back to full height
- re-interlace

It worked pretty well, but had some artifacts that might be corrected with a more complete solution like integration with yadif.

**Comment by Asd-g** [comment]
Hi, I don't see how rife could be integrated in yadif/bwdif or similar deinterlacers. Something similar is done already in the spatial domain with `edeint` but it's different for the temporal one.

Deinterlacing scripts like QTGMC/MCBob could more suitable for such integration.

**Comment by ryanfelder** [comment]
Thanks for the followup
